# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

clone_depth: 1

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.12"

cache:
  - bower_components
  - node_modules

branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # hide python so node-gyp won't try to build native extentions
  - rename C:\Python27 Python27hidden
  # Typical npm stuff.
  - md C:\nc
  - npm version
  - npm config set cache C:\nc
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install --no-optional --no-bin-links
  - bower install

# Testing is currently disabled, because AppVeyor isn't fast enough
test: off

# Build scripts.
build_script:
  # Output useful info for debugging.
  - npm version
  - grunt createWinDevBuild
  # Currently no test: Ember-Electron has trouble on Windows

deploy_script:
  - grunt deployWinDevBuild

# Set build version format here instead of in the admin panel.
version: "{build}"